/*import { apiGet } from '../generic/apiCall';
export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD';

export function fetchDashboardData() {
  return dispatch => {
    apiGet('/api/dashboard', null, dispatch)
      .then(json => dispatch({
        type: UPDATE_DASHBOARD,
        data: json
      }))
      .catch(err => console.log('catched eror', err));
  };
}
*/
import { apiGet } from '../generic/apiCall';
export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD';

const dashboard = {
	"keys": {
		"ownKeys": [{
			"currencies": [{
				"name": "USDT",
				"amount": "4.76"
			}, {
				"name": "BTC",
				"amount": "91.56"
			}, {
				"name": "ETH",
				"amount": "50.50"
			}, {
				"name": "BCC",
				"amount": "97.20"
			}, {
				"name": "OMG",
				"amount": "64.65"
			}, {
				"name": "STRAT",
				"amount": "53.12"
			}, {
				"name": "XRP",
				"amount": "59.27"
			}, {
				"name": "PAY",
				"amount": "71.80"
			}, {
				"name": "ZEC",
				"amount": "39.37"
			}, {
				"name": "GBYTE",
				"amount": "61.78"
			}, {
				"name": "NXT",
				"amount": "7.92"
			}, {
				"name": "XEM",
				"amount": "91.20"
			}, {
				"name": "SC",
				"amount": "49.24"
			}, {
				"name": "DGB",
				"amount": "56.51"
			}, {
				"name": "WAVES",
				"amount": "36.57"
			}, {
				"name": "GLD",
				"amount": "61.93"
			}, {
				"name": "CVC",
				"amount": "11.34"
			}, {
				"name": "NMR",
				"amount": "4.38"
			}, {
				"name": "BAT",
				"amount": "11.90"
			}, {
				"name": "LSK",
				"amount": "19.64"
			}, {
				"name": "XEL",
				"amount": "66.51"
			}, {
				"name": "REP",
				"amount": "88.57"
			}, {
				"name": "PIVX",
				"amount": "27.09"
			}, {
				"name": "FCT",
				"amount": "33.89"
			}, {
				"name": "SNT",
				"amount": "13.76"
			}, {
				"name": "DCR",
				"amount": "1.45"
			}, {
				"name": "ARDR",
				"amount": "84.18"
			}, {
				"name": "KORE",
				"amount": "86.25"
			}, {
				"name": "STORJ",
				"amount": "43.20"
			}, {
				"name": "ANT",
				"amount": "13.34"
			}, {
				"name": "FUN",
				"amount": "24.66"
			}, {
				"name": "BNT",
				"amount": "53.20"
			}, {
				"name": "PTOY",
				"amount": "72.71"
			}, {
				"name": "DRACO",
				"amount": "65.40"
			}, {
				"name": "AMP",
				"amount": "73.74"
			}, {
				"name": "EFL",
				"amount": "65.34"
			}, {
				"name": "PART",
				"amount": "6.10"
			}, {
				"name": "TRST ",
				"amount": "36.31"
			}, {
				"name": "KMD",
				"amount": "88.80"
			}, {
				"name": "MAID",
				"amount": "14.63"
			}, {
				"name": "SYS",
				"amount": "3.89"
			}, {
				"name": "VIA",
				"amount": "37.31"
			}, {
				"name": "DGD",
				"amount": "68.24"
			}, {
				"name": "MUE",
				"amount": "57.30"
			}, {
				"name": "HMQ",
				"amount": "82.31"
			}, {
				"name": "UBQ",
				"amount": "82.11"
			}, {
				"name": "ABY",
				"amount": "45.01"
			}, {
				"name": "OMNI",
				"amount": "98.69"
			}, {
				"name": "RLC",
				"amount": "65.01"
			}, {
				"name": "GNO",
				"amount": "21.96"
			}, {
				"name": "HKG ",
				"amount": "74.72"
			}, {
				"name": "CFI",
				"amount": "22.08"
			}, {
				"name": "NAV",
				"amount": "49.59"
			}, {
				"name": "XWC",
				"amount": "97.54"
			}, {
				"name": "DCT",
				"amount": "47.41"
			}, {
				"name": "VRC",
				"amount": "26.77"
			}, {
				"name": "MYST",
				"amount": "94.03"
			}, {
				"name": "EDG",
				"amount": "31.56"
			}, {
				"name": "NLG",
				"amount": "44.59"
			}, {
				"name": "IOP",
				"amount": "95.71"
			}, {
				"name": "MEME",
				"amount": "22.55"
			}, {
				"name": "SNGLS",
				"amount": "68.78"
			}, {
				"name": "ZCL",
				"amount": "93.91"
			}, {
				"name": "SPHR ",
				"amount": "52.96"
			}, {
				"name": "TKN",
				"amount": "83.16"
			}, {
				"name": "RADS",
				"amount": "40.77"
			}, {
				"name": "BAY",
				"amount": "44.78"
			}, {
				"name": "SYNX",
				"amount": "84.02"
			}, {
				"name": "GBG",
				"amount": "45.16"
			}, {
				"name": "LUN",
				"amount": "82.50"
			}, {
				"name": "MLN",
				"amount": "85.47"
			}, {
				"name": "SPR",
				"amount": "92.61"
			}, {
				"name": "SIB",
				"amount": "91.48"
			}, {
				"name": "NBT",
				"amount": "45.23"
			}, {
				"name": "CRW",
				"amount": "5.94"
			}, {
				"name": "GRS",
				"amount": "87.48"
			}, {
				"name": "MUSIC",
				"amount": "54.67"
			}, {
				"name": "ADT",
				"amount": "91.74"
			}, {
				"name": "BLK",
				"amount": "80.10"
			}, {
				"name": "XCP",
				"amount": "6.97"
			}, {
				"name": "BITB",
				"amount": "55.18"
			}, {
				"name": "VRM",
				"amount": "80.07"
			}, {
				"name": "SHIFT",
				"amount": "24.49"
			}, {
				"name": "MONA",
				"amount": "6.86"
			}, {
				"name": "XAUR",
				"amount": "85.73"
			}, {
				"name": "ADX",
				"amount": "2.33"
			}, {
				"name": "INFX",
				"amount": "82.86"
			}, {
				"name": "AGRS",
				"amount": "29.53"
			}, {
				"name": "GEO",
				"amount": "16.54"
			}, {
				"name": "APX",
				"amount": "42.58"
			}, {
				"name": "FTC",
				"amount": "77.51"
			}, {
				"name": "THC",
				"amount": "77.77"
			}, {
				"name": "GOLOS",
				"amount": "3.37"
			}, {
				"name": "OK",
				"amount": "80.57"
			}, {
				"name": "UNB ",
				"amount": "0.39"
			}, {
				"name": "DAR",
				"amount": "91.45"
			}, {
				"name": "COVAL",
				"amount": "68.22"
			}, {
				"name": "PDC",
				"amount": "0.64"
			}, {
				"name": "RISE",
				"amount": "47.95"
			}, {
				"name": "NXC",
				"amount": "45.08"
			}, {
				"name": "NEOS",
				"amount": "61.37"
			}, {
				"name": "PPC",
				"amount": "30.88"
			}, {
				"name": "DYN",
				"amount": "83.13"
			}, {
				"name": "QWARK",
				"amount": "11.31"
			}, {
				"name": "LMC",
				"amount": "11.82"
			}, {
				"name": "CLUB",
				"amount": "4.15"
			}, {
				"name": "SBD",
				"amount": "26.48"
			}, {
				"name": "DMD",
				"amount": "98.80"
			}, {
				"name": "CURE",
				"amount": "9.11"
			}, {
				"name": "PKB",
				"amount": "58.17"
			}, {
				"name": "TIME",
				"amount": "57.31"
			}, {
				"name": "CANN",
				"amount": "95.43"
			}, {
				"name": "EGC",
				"amount": "88.53"
			}, {
				"name": "DOPE",
				"amount": "15.13"
			}, {
				"name": "AEON",
				"amount": "94.29"
			}, {
				"name": "CRB",
				"amount": "3.84"
			}, {
				"name": "XVC",
				"amount": "83.65"
			}, {
				"name": "TRUST",
				"amount": "7.84"
			}, {
				"name": "SWT",
				"amount": "1.00"
			}, {
				"name": "RBY",
				"amount": "58.71"
			}, {
				"name": "TX",
				"amount": "91.07"
			}, {
				"name": "FLO",
				"amount": "46.92"
			}, {
				"name": "BRX",
				"amount": "9.39"
			}, {
				"name": "BSD",
				"amount": "80.37"
			}, {
				"name": "2GIVE",
				"amount": "70.33"
			}, {
				"name": "TRIG",
				"amount": "93.66"
			}, {
				"name": "ERC",
				"amount": "11.09"
			}, {
				"name": "SLR",
				"amount": "79.98"
			}, {
				"name": "AUR",
				"amount": "38.49"
			}, {
				"name": "GAM",
				"amount": "84.67"
			}, {
				"name": "TKS",
				"amount": "72.80"
			}],
			"state": "FREE",
			"owner": "27c2fb5948d2f8d7ec6d782e",
			"name": "MyFreeKey",
			"exchange": "bittrex",
			"key": "829ab7db6b4f7a11c5c9d47f",
			"_id": "69b08297e23344e98db13af8"
		}, {
			"currencies": [{
				"name": "USDT",
				"amount": "87.06"
			}, {
				"name": "BTC",
				"amount": "78.45"
			}, {
				"name": "ETH",
				"amount": "5.66"
			}, {
				"name": "LGD",
				"amount": "56.21"
			}, {
				"name": "OMG",
				"amount": "18.58"
			}, {
				"name": "LTC",
				"amount": "65.28"
			}, {
				"name": "XRP",
				"amount": "76.05"
			}, {
				"name": "PAY",
				"amount": "83.38"
			}, {
				"name": "GBYTE",
				"amount": "48.10"
			}, {
				"name": "SC",
				"amount": "94.92"
			}, {
				"name": "DGB",
				"amount": "7.05"
			}, {
				"name": "ETC",
				"amount": "34.54"
			}, {
				"name": "WAVES",
				"amount": "19.99"
			}, {
				"name": "GLD",
				"amount": "89.82"
			}, {
				"name": "DASH",
				"amount": "71.86"
			}, {
				"name": "GNT",
				"amount": "24.81"
			}, {
				"name": "CVC",
				"amount": "4.29"
			}, {
				"name": "1ST",
				"amount": "50.50"
			}, {
				"name": "NMR",
				"amount": "59.32"
			}, {
				"name": "LSK",
				"amount": "52.32"
			}, {
				"name": "XEL",
				"amount": "89.86"
			}, {
				"name": "BTS",
				"amount": "99.43"
			}, {
				"name": "XVG",
				"amount": "99.69"
			}, {
				"name": "REP",
				"amount": "69.78"
			}, {
				"name": "LBC",
				"amount": "20.46"
			}, {
				"name": "PIVX",
				"amount": "87.13"
			}, {
				"name": "FCT",
				"amount": "33.25"
			}, {
				"name": "SNT",
				"amount": "88.06"
			}, {
				"name": "DCR",
				"amount": "6.58"
			}, {
				"name": "ARDR",
				"amount": "30.63"
			}, {
				"name": "BLOCK",
				"amount": "60.84"
			}, {
				"name": "RDD",
				"amount": "5.01"
			}, {
				"name": "KORE",
				"amount": "64.47"
			}, {
				"name": "WINGS",
				"amount": "20.17"
			}, {
				"name": "ARK",
				"amount": "19.87"
			}, {
				"name": "MTL",
				"amount": "2.52"
			}, {
				"name": "BNT",
				"amount": "29.37"
			}, {
				"name": "XZC",
				"amount": "45.62"
			}, {
				"name": "PTOY",
				"amount": "13.81"
			}, {
				"name": "STEEM",
				"amount": "44.48"
			}, {
				"name": "DRACO",
				"amount": "5.33"
			}, {
				"name": "QRL",
				"amount": "9.17"
			}, {
				"name": "AMP",
				"amount": "92.41"
			}, {
				"name": "TRST ",
				"amount": "37.45"
			}, {
				"name": "KMD",
				"amount": "72.14"
			}, {
				"name": "MAID",
				"amount": "16.97"
			}, {
				"name": "SYS",
				"amount": "35.84"
			}, {
				"name": "VIA",
				"amount": "32.85"
			}, {
				"name": "DGD",
				"amount": "96.07"
			}, {
				"name": "MUE",
				"amount": "94.46"
			}, {
				"name": "HMQ",
				"amount": "30.93"
			}, {
				"name": "VOX",
				"amount": "37.20"
			}, {
				"name": "UBQ",
				"amount": "84.49"
			}, {
				"name": "XMY",
				"amount": "5.59"
			}, {
				"name": "MCO",
				"amount": "15.84"
			}, {
				"name": "ABY",
				"amount": "4.36"
			}, {
				"name": "RLC",
				"amount": "99.82"
			}, {
				"name": "GNO",
				"amount": "82.55"
			}, {
				"name": "EMC2",
				"amount": "76.57"
			}, {
				"name": "HKG ",
				"amount": "1.65"
			}, {
				"name": "CFI",
				"amount": "67.49"
			}, {
				"name": "BTA",
				"amount": "79.86"
			}, {
				"name": "NAV",
				"amount": "69.00"
			}, {
				"name": "XWC",
				"amount": "77.08"
			}, {
				"name": "DCT",
				"amount": "56.58"
			}, {
				"name": "NXS",
				"amount": "60.35"
			}, {
				"name": "VRC",
				"amount": "96.08"
			}, {
				"name": "MYST",
				"amount": "1.95"
			}, {
				"name": "EDG",
				"amount": "92.82"
			}, {
				"name": "NLG",
				"amount": "52.72"
			}, {
				"name": "VTC",
				"amount": "66.04"
			}, {
				"name": "CLOAK",
				"amount": "9.94"
			}, {
				"name": "ZEN",
				"amount": "15.05"
			}, {
				"name": "MEME",
				"amount": "99.07"
			}, {
				"name": "SNGLS",
				"amount": "6.16"
			}, {
				"name": "DTB",
				"amount": "61.95"
			}, {
				"name": "ZCL",
				"amount": "39.04"
			}, {
				"name": "TKN",
				"amount": "33.42"
			}, {
				"name": "BAY",
				"amount": "17.94"
			}, {
				"name": "BURST",
				"amount": "63.50"
			}, {
				"name": "GBG",
				"amount": "24.03"
			}, {
				"name": "SLS",
				"amount": "15.09"
			}, {
				"name": "MLN",
				"amount": "38.23"
			}, {
				"name": "SIB",
				"amount": "87.79"
			}, {
				"name": "NBT",
				"amount": "48.14"
			}, {
				"name": "CRW",
				"amount": "99.24"
			}, {
				"name": "GRS",
				"amount": "66.50"
			}, {
				"name": "CPC",
				"amount": "0.60"
			}, {
				"name": "ADT",
				"amount": "36.96"
			}, {
				"name": "POT",
				"amount": "65.48"
			}, {
				"name": "XMG",
				"amount": "19.16"
			}, {
				"name": "MONA",
				"amount": "75.75"
			}, {
				"name": "ADX",
				"amount": "26.92"
			}, {
				"name": "AGRS",
				"amount": "35.63"
			}, {
				"name": "GEO",
				"amount": "83.07"
			}, {
				"name": "APX",
				"amount": "82.06"
			}, {
				"name": "BCY",
				"amount": "91.92"
			}, {
				"name": "FTC",
				"amount": "1.46"
			}, {
				"name": "THC",
				"amount": "28.20"
			}, {
				"name": "UNB ",
				"amount": "8.07"
			}, {
				"name": "DAR",
				"amount": "21.07"
			}, {
				"name": "PDC",
				"amount": "88.04"
			}, {
				"name": "RISE",
				"amount": "34.21"
			}, {
				"name": "NXC",
				"amount": "27.36"
			}, {
				"name": "EBST",
				"amount": "0.56"
			}, {
				"name": "NEOS",
				"amount": "23.75"
			}, {
				"name": "PPC",
				"amount": "94.28"
			}, {
				"name": "DYN",
				"amount": "78.39"
			}, {
				"name": "QWARK",
				"amount": "45.80"
			}, {
				"name": "LMC",
				"amount": "91.33"
			}, {
				"name": "XST",
				"amount": "74.27"
			}, {
				"name": "CLUB",
				"amount": "51.25"
			}, {
				"name": "GRC",
				"amount": "29.54"
			}, {
				"name": "START",
				"amount": "27.81"
			}, {
				"name": "SBD",
				"amount": "62.79"
			}, {
				"name": "DMD",
				"amount": "35.16"
			}, {
				"name": "CURE",
				"amount": "90.29"
			}, {
				"name": "PKB",
				"amount": "19.09"
			}, {
				"name": "TIME",
				"amount": "73.99"
			}, {
				"name": "INCNT",
				"amount": "69.41"
			}, {
				"name": "CANN",
				"amount": "51.05"
			}, {
				"name": "EGC",
				"amount": "91.51"
			}, {
				"name": "BTCD",
				"amount": "2.89"
			}, {
				"name": "DOPE",
				"amount": "88.70"
			}, {
				"name": "UNO",
				"amount": "39.78"
			}, {
				"name": "CRB",
				"amount": "76.56"
			}, {
				"name": "GCR",
				"amount": "1.99"
			}, {
				"name": "NAUT",
				"amount": "99.34"
			}, {
				"name": "TRUST",
				"amount": "97.83"
			}, {
				"name": "SWT",
				"amount": "73.89"
			}, {
				"name": "RBY",
				"amount": "25.83"
			}, {
				"name": "FLDC ",
				"amount": "61.14"
			}, {
				"name": "ENRG",
				"amount": "97.64"
			}, {
				"name": "TX",
				"amount": "10.68"
			}, {
				"name": "FLO",
				"amount": "78.53"
			}, {
				"name": "VTR",
				"amount": "41.61"
			}, {
				"name": "BRX",
				"amount": "33.53"
			}, {
				"name": "BSD",
				"amount": "59.07"
			}, {
				"name": "PTC",
				"amount": "18.18"
			}, {
				"name": "2GIVE",
				"amount": "64.87"
			}, {
				"name": "TRIG",
				"amount": "85.62"
			}, {
				"name": "ERC",
				"amount": "94.06"
			}, {
				"name": "SLR",
				"amount": "18.41"
			}, {
				"name": "AUR",
				"amount": "24.51"
			}, {
				"name": "SWIFT",
				"amount": "16.11"
			}, {
				"name": "CLAM",
				"amount": "99.85"
			}],
			"state": "NOT_FREE",
			"owner": "27c2fb5948d2f8d7ec6d782e",
			"name": "MyOfferKey",
			"exchange": "bittrex",
			"key": "9ca558b05a19a2fb31580203",
			"_id": "bb40cfcacf99cc29995cceb9"
		}, {
			"currencies": [{
				"name": "USDT",
				"amount": "5.31"
			}, {
				"name": "BTC",
				"amount": "79.89"
			}, {
				"name": "ETH",
				"amount": "43.93"
			}, {
				"name": "NEO",
				"amount": "85.93"
			}, {
				"name": "BCC",
				"amount": "42.51"
			}, {
				"name": "LGD",
				"amount": "85.00"
			}, {
				"name": "OMG",
				"amount": "46.80"
			}, {
				"name": "STRAT",
				"amount": "34.72"
			}, {
				"name": "XRP",
				"amount": "86.55"
			}, {
				"name": "QTUM",
				"amount": "28.26"
			}, {
				"name": "PAY",
				"amount": "16.41"
			}, {
				"name": "ZEC",
				"amount": "2.58"
			}, {
				"name": "GBYTE",
				"amount": "57.15"
			}, {
				"name": "NXT",
				"amount": "61.45"
			}, {
				"name": "XEM",
				"amount": "9.72"
			}, {
				"name": "SC",
				"amount": "11.41"
			}, {
				"name": "ETC",
				"amount": "60.06"
			}, {
				"name": "GLD",
				"amount": "63.80"
			}, {
				"name": "DASH",
				"amount": "17.85"
			}, {
				"name": "GNT",
				"amount": "94.95"
			}, {
				"name": "CVC",
				"amount": "18.22"
			}, {
				"name": "1ST",
				"amount": "29.31"
			}, {
				"name": "NMR",
				"amount": "65.10"
			}, {
				"name": "BAT",
				"amount": "95.55"
			}, {
				"name": "LSK",
				"amount": "52.74"
			}, {
				"name": "BTS",
				"amount": "9.76"
			}, {
				"name": "XVG",
				"amount": "29.01"
			}, {
				"name": "LBC",
				"amount": "64.96"
			}, {
				"name": "PIVX",
				"amount": "21.41"
			}, {
				"name": "SNT",
				"amount": "99.54"
			}, {
				"name": "DCR",
				"amount": "99.37"
			}, {
				"name": "BLOCK",
				"amount": "84.80"
			}, {
				"name": "RDD",
				"amount": "77.08"
			}, {
				"name": "STORJ",
				"amount": "89.69"
			}, {
				"name": "ARK",
				"amount": "34.97"
			}, {
				"name": "ANT",
				"amount": "20.05"
			}, {
				"name": "MTL",
				"amount": "48.96"
			}, {
				"name": "FUN",
				"amount": "4.47"
			}, {
				"name": "XLM",
				"amount": "23.11"
			}, {
				"name": "EXCL",
				"amount": "60.18"
			}, {
				"name": "BNT",
				"amount": "8.11"
			}, {
				"name": "STEEM",
				"amount": "22.35"
			}, {
				"name": "DRACO",
				"amount": "97.58"
			}, {
				"name": "AMP",
				"amount": "38.18"
			}, {
				"name": "EFL",
				"amount": "1.68"
			}, {
				"name": "PART",
				"amount": "67.56"
			}, {
				"name": "KMD",
				"amount": "71.56"
			}, {
				"name": "SYS",
				"amount": "79.42"
			}, {
				"name": "VIA",
				"amount": "71.88"
			}, {
				"name": "IOC",
				"amount": "2.36"
			}, {
				"name": "DOGE",
				"amount": "55.51"
			}, {
				"name": "DGD",
				"amount": "70.82"
			}, {
				"name": "MUE",
				"amount": "42.55"
			}, {
				"name": "HMQ",
				"amount": "20.13"
			}, {
				"name": "VOX",
				"amount": "42.14"
			}, {
				"name": "EXP",
				"amount": "73.01"
			}, {
				"name": "UBQ",
				"amount": "25.22"
			}, {
				"name": "RLC",
				"amount": "16.50"
			}, {
				"name": "EMC2",
				"amount": "64.47"
			}, {
				"name": "HKG ",
				"amount": "87.49"
			}, {
				"name": "BRK",
				"amount": "77.14"
			}, {
				"name": "XWC",
				"amount": "95.61"
			}, {
				"name": "DCT",
				"amount": "53.09"
			}, {
				"name": "NXS",
				"amount": "61.17"
			}, {
				"name": "VRC",
				"amount": "91.46"
			}, {
				"name": "MYST",
				"amount": "12.66"
			}, {
				"name": "EDG",
				"amount": "70.91"
			}, {
				"name": "VTC",
				"amount": "20.10"
			}, {
				"name": "IOP",
				"amount": "24.20"
			}, {
				"name": "SNGLS",
				"amount": "89.58"
			}, {
				"name": "DTB",
				"amount": "93.35"
			}, {
				"name": "ZCL",
				"amount": "10.99"
			}, {
				"name": "TKN",
				"amount": "11.37"
			}, {
				"name": "SYNX",
				"amount": "41.97"
			}, {
				"name": "BURST",
				"amount": "23.53"
			}, {
				"name": "GUP",
				"amount": "16.09"
			}, {
				"name": "GBG",
				"amount": "29.98"
			}, {
				"name": "XDN",
				"amount": "50.40"
			}, {
				"name": "SPR",
				"amount": "21.89"
			}, {
				"name": "SIB",
				"amount": "29.54"
			}, {
				"name": "CRW",
				"amount": "11.77"
			}, {
				"name": "GRS",
				"amount": "67.39"
			}, {
				"name": "CPC",
				"amount": "15.98"
			}, {
				"name": "BLK",
				"amount": "92.47"
			}, {
				"name": "POT",
				"amount": "9.82"
			}, {
				"name": "BITB",
				"amount": "90.45"
			}, {
				"name": "XBB",
				"amount": "90.19"
			}, {
				"name": "VRM",
				"amount": "65.61"
			}, {
				"name": "MONA",
				"amount": "34.79"
			}, {
				"name": "XAUR",
				"amount": "7.53"
			}, {
				"name": "AGRS",
				"amount": "69.85"
			}, {
				"name": "BCY",
				"amount": "88.81"
			}, {
				"name": "FTC",
				"amount": "51.41"
			}, {
				"name": "THC",
				"amount": "0.03"
			}, {
				"name": "GOLOS",
				"amount": "31.72"
			}, {
				"name": "OK",
				"amount": "12.79"
			}, {
				"name": "UNB ",
				"amount": "58.06"
			}, {
				"name": "DAR",
				"amount": "64.94"
			}, {
				"name": "PDC",
				"amount": "90.77"
			}, {
				"name": "RISE",
				"amount": "21.55"
			}, {
				"name": "NXC",
				"amount": "17.19"
			}, {
				"name": "NEOS",
				"amount": "45.55"
			}, {
				"name": "PINK",
				"amount": "73.05"
			}, {
				"name": "PPC",
				"amount": "49.29"
			}, {
				"name": "DYN",
				"amount": "13.40"
			}, {
				"name": "QWARK",
				"amount": "72.55"
			}, {
				"name": "CLUB",
				"amount": "63.95"
			}, {
				"name": "GRC",
				"amount": "79.17"
			}, {
				"name": "SBD",
				"amount": "21.93"
			}, {
				"name": "BLITZ ",
				"amount": "98.92"
			}, {
				"name": "PKB",
				"amount": "68.98"
			}, {
				"name": "EGC",
				"amount": "25.17"
			}, {
				"name": "BTCD",
				"amount": "73.82"
			}, {
				"name": "DOPE",
				"amount": "83.75"
			}, {
				"name": "UNO",
				"amount": "39.58"
			}, {
				"name": "AEON",
				"amount": "4.28"
			}, {
				"name": "CRB",
				"amount": "75.40"
			}, {
				"name": "GCR",
				"amount": "28.16"
			}, {
				"name": "NAUT",
				"amount": "64.95"
			}, {
				"name": "XVC",
				"amount": "87.34"
			}, {
				"name": "TRUST",
				"amount": "87.71"
			}, {
				"name": "SWT",
				"amount": "27.50"
			}, {
				"name": "ENRG",
				"amount": "29.85"
			}, {
				"name": "TX",
				"amount": "45.13"
			}, {
				"name": "FLO",
				"amount": "74.33"
			}, {
				"name": "VTR",
				"amount": "50.35"
			}, {
				"name": "BRX",
				"amount": "29.91"
			}, {
				"name": "PTC",
				"amount": "64.30"
			}, {
				"name": "2GIVE",
				"amount": "93.04"
			}, {
				"name": "SNRG",
				"amount": "95.59"
			}, {
				"name": "TRIG",
				"amount": "55.26"
			}, {
				"name": "ERC",
				"amount": "32.08"
			}, {
				"name": "BYC",
				"amount": "35.97"
			}, {
				"name": "SWIFT",
				"amount": "0.51"
			}, {
				"name": "GAM",
				"amount": "2.26"
			}, {
				"name": "CLAM",
				"amount": "93.87"
			}],
			"state": "NOT_FREE",
			"owner": "27c2fb5948d2f8d7ec6d782e",
			"name": "MyContractKey",
			"exchange": "bittrex",
			"key": "76464b1a30d48bbc738c5974",
			"_id": "cf654ee7ca0da720f3ecb772"
		}],
		"receivedKeys": [{
			"currencies": [{
				"name": "USDT",
				"amount": "90.44"
			}, {
				"name": "BTC",
				"amount": "94.41"
			}, {
				"name": "ETH",
				"amount": "57.96"
			}, {
				"name": "NEO",
				"amount": "35.17"
			}, {
				"name": "BCC",
				"amount": "23.41"
			}, {
				"name": "LGD",
				"amount": "11.33"
			}, {
				"name": "OMG",
				"amount": "27.83"
			}, {
				"name": "QTUM",
				"amount": "30.87"
			}, {
				"name": "PAY",
				"amount": "51.41"
			}, {
				"name": "ZEC",
				"amount": "2.25"
			}, {
				"name": "XEM",
				"amount": "52.59"
			}, {
				"name": "SC",
				"amount": "76.26"
			}, {
				"name": "WAVES",
				"amount": "8.04"
			}, {
				"name": "GLD",
				"amount": "27.14"
			}, {
				"name": "SAFEX",
				"amount": "77.96"
			}, {
				"name": "GNT",
				"amount": "55.39"
			}, {
				"name": "1ST",
				"amount": "59.44"
			}, {
				"name": "XMR",
				"amount": "30.42"
			}, {
				"name": "NMR",
				"amount": "76.95"
			}, {
				"name": "BAT",
				"amount": "9.08"
			}, {
				"name": "LSK",
				"amount": "56.19"
			}, {
				"name": "XEL",
				"amount": "97.40"
			}, {
				"name": "BTS",
				"amount": "25.28"
			}, {
				"name": "XVG",
				"amount": "88.55"
			}, {
				"name": "GAME",
				"amount": "46.50"
			}, {
				"name": "PIVX",
				"amount": "40.41"
			}, {
				"name": "FCT",
				"amount": "33.55"
			}, {
				"name": "SNT",
				"amount": "92.44"
			}, {
				"name": "ARDR",
				"amount": "21.36"
			}, {
				"name": "BLOCK",
				"amount": "7.74"
			}, {
				"name": "RDD",
				"amount": "74.57"
			}, {
				"name": "KORE",
				"amount": "34.21"
			}, {
				"name": "STORJ",
				"amount": "2.31"
			}, {
				"name": "ARK",
				"amount": "77.81"
			}, {
				"name": "ANT",
				"amount": "6.93"
			}, {
				"name": "FUN",
				"amount": "42.66"
			}, {
				"name": "BNT",
				"amount": "53.48"
			}, {
				"name": "PTOY",
				"amount": "57.68"
			}, {
				"name": "STEEM",
				"amount": "4.01"
			}, {
				"name": "DRACO",
				"amount": "69.79"
			}, {
				"name": "AMP",
				"amount": "40.34"
			}, {
				"name": "EFL",
				"amount": "38.34"
			}, {
				"name": "PART",
				"amount": "6.90"
			}, {
				"name": "TRST ",
				"amount": "14.86"
			}, {
				"name": "SYS",
				"amount": "69.91"
			}, {
				"name": "VIA",
				"amount": "26.67"
			}, {
				"name": "IOC",
				"amount": "68.94"
			}, {
				"name": "DOGE",
				"amount": "9.32"
			}, {
				"name": "DGD",
				"amount": "57.35"
			}, {
				"name": "MUE",
				"amount": "92.20"
			}, {
				"name": "VOX",
				"amount": "92.32"
			}, {
				"name": "EXP",
				"amount": "0.01"
			}, {
				"name": "UBQ",
				"amount": "45.12"
			}, {
				"name": "MCO",
				"amount": "75.35"
			}, {
				"name": "ABY",
				"amount": "42.92"
			}, {
				"name": "OMNI",
				"amount": "53.58"
			}, {
				"name": "RLC",
				"amount": "91.90"
			}, {
				"name": "HKG ",
				"amount": "52.02"
			}, {
				"name": "CFI",
				"amount": "79.40"
			}, {
				"name": "BRK",
				"amount": "0.83"
			}, {
				"name": "DCT",
				"amount": "7.02"
			}, {
				"name": "NXS",
				"amount": "40.15"
			}, {
				"name": "MYST",
				"amount": "48.31"
			}, {
				"name": "EDG",
				"amount": "7.42"
			}, {
				"name": "NLG",
				"amount": "73.40"
			}, {
				"name": "CLOAK",
				"amount": "95.92"
			}, {
				"name": "ZEN",
				"amount": "13.56"
			}, {
				"name": "MEME",
				"amount": "72.12"
			}, {
				"name": "DTB",
				"amount": "76.06"
			}, {
				"name": "ZCL",
				"amount": "53.45"
			}, {
				"name": "TKN",
				"amount": "84.99"
			}, {
				"name": "SYNX",
				"amount": "46.23"
			}, {
				"name": "BURST",
				"amount": "50.37"
			}, {
				"name": "LUN",
				"amount": "94.01"
			}, {
				"name": "SLS",
				"amount": "70.27"
			}, {
				"name": "MLN",
				"amount": "38.64"
			}, {
				"name": "SPR",
				"amount": "4.34"
			}, {
				"name": "SIB",
				"amount": "13.76"
			}, {
				"name": "NBT",
				"amount": "41.90"
			}, {
				"name": "CRW",
				"amount": "61.06"
			}, {
				"name": "CPC",
				"amount": "58.83"
			}, {
				"name": "MUSIC",
				"amount": "4.59"
			}, {
				"name": "ADT",
				"amount": "39.37"
			}, {
				"name": "BLK",
				"amount": "21.92"
			}, {
				"name": "POT",
				"amount": "91.83"
			}, {
				"name": "BITB",
				"amount": "93.31"
			}, {
				"name": "XMG",
				"amount": "10.42"
			}, {
				"name": "XBB",
				"amount": "42.13"
			}, {
				"name": "VRM",
				"amount": "90.31"
			}, {
				"name": "SHIFT",
				"amount": "80.00"
			}, {
				"name": "ADX",
				"amount": "51.29"
			}, {
				"name": "GEO",
				"amount": "6.18"
			}, {
				"name": "APX",
				"amount": "62.88"
			}, {
				"name": "FTC",
				"amount": "19.45"
			}, {
				"name": "GOLOS",
				"amount": "91.31"
			}, {
				"name": "UNB ",
				"amount": "88.43"
			}, {
				"name": "DAR",
				"amount": "76.16"
			}, {
				"name": "COVAL",
				"amount": "47.72"
			}, {
				"name": "PDC",
				"amount": "10.66"
			}, {
				"name": "NEOS",
				"amount": "64.37"
			}, {
				"name": "PINK",
				"amount": "36.73"
			}, {
				"name": "PPC",
				"amount": "99.87"
			}, {
				"name": "QWARK",
				"amount": "65.90"
			}, {
				"name": "GRC",
				"amount": "57.38"
			}, {
				"name": "START",
				"amount": "34.98"
			}, {
				"name": "SBD",
				"amount": "87.35"
			}, {
				"name": "DMD",
				"amount": "37.98"
			}, {
				"name": "BLITZ ",
				"amount": "62.87"
			}, {
				"name": "PKB",
				"amount": "82.59"
			}, {
				"name": "INCNT",
				"amount": "39.21"
			}, {
				"name": "CANN",
				"amount": "11.98"
			}, {
				"name": "EGC",
				"amount": "81.89"
			}, {
				"name": "BTCD",
				"amount": "3.24"
			}, {
				"name": "UNO",
				"amount": "25.02"
			}, {
				"name": "AEON",
				"amount": "18.98"
			}, {
				"name": "CRB",
				"amount": "11.94"
			}, {
				"name": "GCR",
				"amount": "89.13"
			}, {
				"name": "XVC",
				"amount": "8.10"
			}, {
				"name": "TRUST",
				"amount": "91.02"
			}, {
				"name": "RBY",
				"amount": "31.38"
			}, {
				"name": "ENRG",
				"amount": "28.31"
			}, {
				"name": "TX",
				"amount": "50.57"
			}, {
				"name": "FLO",
				"amount": "38.46"
			}, {
				"name": "VTR",
				"amount": "99.76"
			}, {
				"name": "BRX",
				"amount": "72.01"
			}, {
				"name": "TRIG",
				"amount": "49.96"
			}, {
				"name": "BYC",
				"amount": "83.96"
			}, {
				"name": "SEQ",
				"amount": "90.48"
			}, {
				"name": "SLR",
				"amount": "10.12"
			}, {
				"name": "AUR",
				"amount": "49.88"
			}, {
				"name": "SWIFT",
				"amount": "93.66"
			}, {
				"name": "GAM",
				"amount": "40.56"
			}, {
				"name": "TKS",
				"amount": "23.19"
			}],
			"state": "NOT_FREE",
			"owner": "a17cfd7df1156a09e0f9f8b0",
			"name": "ReceivedOffer",
			"exchange": "bittrex",
			"key": "5e55a877f63a341de89376e2",
			"_id": "58eedc365972ac68826e68ca"
		}, {
			"currencies": [{
				"name": "USDT",
				"amount": "69.23"
			}, {
				"name": "BTC",
				"amount": "42.33"
			}, {
				"name": "ETH",
				"amount": "57.57"
			}, {
				"name": "NEO",
				"amount": "97.34"
			}, {
				"name": "BCC",
				"amount": "71.83"
			}, {
				"name": "LGD",
				"amount": "16.15"
			}, {
				"name": "OMG",
				"amount": "30.73"
			}, {
				"name": "STRAT",
				"amount": "82.90"
			}, {
				"name": "XRP",
				"amount": "46.97"
			}, {
				"name": "QTUM",
				"amount": "95.36"
			}, {
				"name": "GBYTE",
				"amount": "39.07"
			}, {
				"name": "NXT",
				"amount": "15.80"
			}, {
				"name": "XEM",
				"amount": "38.97"
			}, {
				"name": "SC",
				"amount": "89.36"
			}, {
				"name": "ETC",
				"amount": "33.27"
			}, {
				"name": "WAVES",
				"amount": "15.71"
			}, {
				"name": "GLD",
				"amount": "87.15"
			}, {
				"name": "DASH",
				"amount": "89.19"
			}, {
				"name": "GNT",
				"amount": "97.37"
			}, {
				"name": "CVC",
				"amount": "26.19"
			}, {
				"name": "1ST",
				"amount": "75.37"
			}, {
				"name": "XMR",
				"amount": "22.80"
			}, {
				"name": "NMR",
				"amount": "91.66"
			}, {
				"name": "BAT",
				"amount": "21.08"
			}, {
				"name": "LSK",
				"amount": "17.54"
			}, {
				"name": "BTS",
				"amount": "28.03"
			}, {
				"name": "XVG",
				"amount": "3.47"
			}, {
				"name": "GAME",
				"amount": "18.87"
			}, {
				"name": "REP",
				"amount": "9.13"
			}, {
				"name": "LBC",
				"amount": "6.96"
			}, {
				"name": "PIVX",
				"amount": "85.59"
			}, {
				"name": "SNT",
				"amount": "0.59"
			}, {
				"name": "ARDR",
				"amount": "80.61"
			}, {
				"name": "BLOCK",
				"amount": "69.52"
			}, {
				"name": "RDD",
				"amount": "45.54"
			}, {
				"name": "KORE",
				"amount": "7.42"
			}, {
				"name": "STORJ",
				"amount": "7.99"
			}, {
				"name": "WINGS",
				"amount": "30.79"
			}, {
				"name": "ANT",
				"amount": "52.49"
			}, {
				"name": "XLM",
				"amount": "85.24"
			}, {
				"name": "EXCL",
				"amount": "57.83"
			}, {
				"name": "BNT",
				"amount": "94.13"
			}, {
				"name": "XZC",
				"amount": "48.75"
			}, {
				"name": "PTOY",
				"amount": "78.75"
			}, {
				"name": "STEEM",
				"amount": "85.85"
			}, {
				"name": "DRACO",
				"amount": "19.68"
			}, {
				"name": "QRL",
				"amount": "40.17"
			}, {
				"name": "PART",
				"amount": "33.21"
			}, {
				"name": "TRST ",
				"amount": "85.53"
			}, {
				"name": "KMD",
				"amount": "68.86"
			}, {
				"name": "MAID",
				"amount": "94.37"
			}, {
				"name": "VIA",
				"amount": "28.24"
			}, {
				"name": "DOGE",
				"amount": "25.45"
			}, {
				"name": "DGD",
				"amount": "2.27"
			}, {
				"name": "MUE",
				"amount": "26.98"
			}, {
				"name": "HMQ",
				"amount": "74.32"
			}, {
				"name": "VOX",
				"amount": "77.52"
			}, {
				"name": "EXP",
				"amount": "55.42"
			}, {
				"name": "UBQ",
				"amount": "25.23"
			}, {
				"name": "XMY",
				"amount": "33.11"
			}, {
				"name": "ABY",
				"amount": "31.44"
			}, {
				"name": "OMNI",
				"amount": "65.12"
			}, {
				"name": "RLC",
				"amount": "30.79"
			}, {
				"name": "HKG ",
				"amount": "8.93"
			}, {
				"name": "CFI",
				"amount": "27.48"
			}, {
				"name": "BTA",
				"amount": "9.15"
			}, {
				"name": "NAV",
				"amount": "16.46"
			}, {
				"name": "BRK",
				"amount": "65.85"
			}, {
				"name": "XWC",
				"amount": "41.49"
			}, {
				"name": "DCT",
				"amount": "80.36"
			}, {
				"name": "MYST",
				"amount": "70.10"
			}, {
				"name": "EDG",
				"amount": "49.24"
			}, {
				"name": "NLG",
				"amount": "3.92"
			}, {
				"name": "VTC",
				"amount": "50.19"
			}, {
				"name": "IOP",
				"amount": "92.77"
			}, {
				"name": "MEME",
				"amount": "63.26"
			}, {
				"name": "DTB",
				"amount": "88.68"
			}, {
				"name": "TKN",
				"amount": "18.48"
			}, {
				"name": "RADS",
				"amount": "86.84"
			}, {
				"name": "SYNX",
				"amount": "0.58"
			}, {
				"name": "BURST",
				"amount": "52.80"
			}, {
				"name": "GUP",
				"amount": "11.36"
			}, {
				"name": "LUN",
				"amount": "9.07"
			}, {
				"name": "SLS",
				"amount": "12.47"
			}, {
				"name": "MLN",
				"amount": "69.57"
			}, {
				"name": "SPR",
				"amount": "34.24"
			}, {
				"name": "SIB",
				"amount": "46.83"
			}, {
				"name": "CRW",
				"amount": "27.49"
			}, {
				"name": "GRS",
				"amount": "17.49"
			}, {
				"name": "MUSIC",
				"amount": "80.47"
			}, {
				"name": "ADT",
				"amount": "36.62"
			}, {
				"name": "BLK",
				"amount": "2.66"
			}, {
				"name": "BITB",
				"amount": "23.12"
			}, {
				"name": "XMG",
				"amount": "90.24"
			}, {
				"name": "VRM",
				"amount": "86.95"
			}, {
				"name": "INFX",
				"amount": "42.63"
			}, {
				"name": "APX",
				"amount": "91.95"
			}, {
				"name": "BCY",
				"amount": "67.99"
			}, {
				"name": "FTC",
				"amount": "68.69"
			}, {
				"name": "OK",
				"amount": "96.51"
			}, {
				"name": "COVAL",
				"amount": "91.31"
			}, {
				"name": "PDC",
				"amount": "1.46"
			}, {
				"name": "RISE",
				"amount": "9.58"
			}, {
				"name": "PINK",
				"amount": "79.37"
			}, {
				"name": "PPC",
				"amount": "45.81"
			}, {
				"name": "LMC",
				"amount": "58.77"
			}, {
				"name": "GRC",
				"amount": "93.59"
			}, {
				"name": "START",
				"amount": "33.51"
			}, {
				"name": "SBD",
				"amount": "46.74"
			}, {
				"name": "DMD",
				"amount": "15.73"
			}, {
				"name": "BLITZ ",
				"amount": "91.94"
			}, {
				"name": "DOPE",
				"amount": "6.49"
			}, {
				"name": "UNO",
				"amount": "96.40"
			}, {
				"name": "AEON",
				"amount": "60.89"
			}, {
				"name": "FAIR",
				"amount": "29.82"
			}, {
				"name": "GCR",
				"amount": "85.53"
			}, {
				"name": "NAUT",
				"amount": "10.52"
			}, {
				"name": "TRUST",
				"amount": "95.10"
			}, {
				"name": "EMC",
				"amount": "93.76"
			}, {
				"name": "FLDC ",
				"amount": "13.87"
			}, {
				"name": "ENRG",
				"amount": "7.55"
			}, {
				"name": "TX",
				"amount": "0.55"
			}, {
				"name": "VTR",
				"amount": "80.49"
			}, {
				"name": "PTC",
				"amount": "20.28"
			}, {
				"name": "2GIVE",
				"amount": "24.18"
			}, {
				"name": "SNRG",
				"amount": "47.68"
			}, {
				"name": "TRIG",
				"amount": "46.48"
			}, {
				"name": "ERC",
				"amount": "79.64"
			}, {
				"name": "BYC",
				"amount": "83.18"
			}, {
				"name": "SEQ",
				"amount": "30.19"
			}, {
				"name": "SLR",
				"amount": "39.80"
			}, {
				"name": "SWIFT",
				"amount": "72.94"
			}, {
				"name": "GAM",
				"amount": "53.25"
			}],
			"state": "NOT_FREE",
			"owner": "652ced76600a3a0b4de86524",
			"name": "ReceivedContract",
			"exchange": "bittrex",
			"key": "b66a84ea76af5d04209a8b64",
			"_id": "a9d417be0eac6ab1a87e7176"
		}]
	},
	"contracts": [{
		"contractor": "SOME_TRADER",
		"currency": "BTC",
		"status": "in_progress",
		"expireDate": 1517350968772.1692,
		"startDate": 1507560205638.8174,
		"startBalance": 88,
		"currentBalance": 108,
		"left": 3,
		"maxLoss": 27,
		"fee": 16,
		"_id": "4f56a247d29ce75eb0ebc11c",
		"keyId": "cf654ee7ca0da720f3ecb772"
	}, {
		"contractor": "OTHER_TRADER",
		"currency": "USDT",
		"status": "completed",
		"expireDate": 1514697331385.3237,
		"startDate": 1507865539013.0283,
		"startBalance": 61,
		"currentBalance": 68,
		"left": 1,
		"maxLoss": 17,
		"fee": 19,
		"_id": "38ccc1a3e9e18105953a7eb2",
		"keyId": "cf654ee7ca0da720f3ecb772"
	}, {
		"contractor": "BEST_TRADER",
		"currency": "BTC",
		"status": "failed",
		"expireDate": 1514983194848.6416,
		"startDate": 1508026089124.9385,
		"startBalance": 101,
		"currentBalance": 95,
		"left": 23,
		"maxLoss": 16,
		"fee": 26,
		"_id": "ebeb0e4d83c6f1d0fb0fcf1b",
		"keyId": "cf654ee7ca0da720f3ecb772"
	}, {
		"contractor": "me",
		"currency": "USDT",
		"status": "in_progress",
		"expireDate": 1514290607546.998,
		"startDate": 1507721587175.3604,
		"startBalance": 71,
		"currentBalance": 67,
		"left": 16,
		"maxLoss": 25,
		"fee": 13,
		"_id": "398633c792e64af2112b4cd6",
		"keyId": "bb40cfcacf99cc29995cceb9"
	}, {
		"contractor": "OTHER_TRADER2",
		"currency": "USDT",
		"status": "completed",
		"expireDate": 1515802617380.2358,
		"startDate": 1508598367242.5405,
		"startBalance": 92,
		"currentBalance": 95,
		"left": 9,
		"maxLoss": 13,
		"fee": 13,
		"_id": "796d132e9410014c4a0dc2d4",
		"keyId": "cf654ee7ca0da720f3ecb772"
	}, {
		"contractor": "OTHER_TRADER3",
		"currency": "USDT",
		"status": "completed",
		"expireDate": 1511008216946.044,
		"startDate": 1507457667387.22,
		"startBalance": 47,
		"currentBalance": 50,
		"left": 9,
		"maxLoss": 24,
		"fee": 27,
		"_id": "9ecccb44d978b75233c5d83c",
		"keyId": "cf654ee7ca0da720f3ecb772"
	}, {
		"contractor": "OTHER_TRADER3",
		"currency": "USDT",
		"status": "completed",
		"expireDate": 1510314353084.5017,
		"startDate": 1508281123041.8767,
		"startBalance": 29,
		"currentBalance": 30,
		"left": 5,
		"maxLoss": 26,
		"fee": 27,
		"_id": "14aaf5eb56c97c689e345552",
		"keyId": "cf654ee7ca0da720f3ecb772"
	}],
	"offers": {
		"incoming": [{
			"_id": "024ec47a9bda5ea9f9a3f744",
			"keyId": "58eedc365972ac68826e68ca",
			"state": "INIT",
			"date": "2017-10-24T07:11:49.668Z",
			"amount": 17,
			"fee": 12,
			"maxLoss": 18,
			"from": "me",
			"to": "other"
		}],
		"outgoing": [{
			"_id": "1b48606c67ba495545f78651",
			"keyId": "bb40cfcacf99cc29995cceb9",
			"state": "INIT",
			"date": "2017-10-23T14:31:53.002Z",
			"amount": 48,
			"fee": 10,
			"maxLoss": 18,
			"from": "me",
			"to": "other"
		}]
	}
}

export function fetchDashboardData() {
  return dispatch => {
    apiGet('/api/dashboard', null, dispatch)
      .then(json => dispatch({
        type: UPDATE_DASHBOARD,
        data: dashboard
      }))
      .catch(err => console.log('catched eror', err));
  };
}
