export default [
  'USDT', 'BTC', 'ETH', 'NEO', 'BCC', 'LGD', 'OMG', 'STRAT', 'LTC', 'XRP',
  'QTUM', 'PAY', 'ZEC', 'GBYTE', 'NXT', 'XEM', 'SC', 'DGB', 'ETC', 'WAVES',
  'GLD', 'SAFEX', 'DASH', 'GNT', 'CVC', '1ST', 'XMR', 'NMR', 'BAT', 'LSK', 'XEL',
  'BTS', 'XVG', 'GAME', 'REP', 'LBC', 'PIVX', 'FCT', 'SNT', 'DCR', 'ARDR', 'BLOCK',
  'RDD', 'KORE', 'STORJ', 'WINGS', 'ARK', 'ANT', 'MTL', 'FUN', 'XLM', 'EXCL', 'BNT',
  'XZC', 'PTOY', 'STEEM', 'DRACO', 'QRL', 'AMP', 'EFL', 'PART', 'TRST ', 'KMD',
  'MAID', 'SYS', 'VIA', 'IOC', 'DOGE', 'DGD', 'MUE', 'HMQ', 'VOX', 'EXP', 'UBQ',
  'XMY', 'MCO', 'ABY', 'OMNI', 'RLC', 'GNO', 'EMC2', 'HKG ', 'CFI', 'BTA', 'NAV',
  'BRK', 'XWC', 'DCT', 'NXS', 'VRC', 'MYST', 'EDG', 'NLG', 'VTC', 'IOP',
  'CLOAK', 'ZEN', 'MEME', 'SNGLS', 'DTB', 'ZCL', 'SPHR ', 'TKN', 'RADS', 'BAY',
  'SYNX', 'BURST', 'GUP', 'GBG', 'LUN', 'SLS', 'MLN', 'XDN', 'SPR', 'SIB',
  'NBT', 'CRW', 'GRS', 'CPC', 'MUSIC', 'ADT', 'BLK', 'POT', 'XCP', 'BITB',
  'XMG', 'XBB', 'VRM', 'SHIFT', 'MONA', 'XAUR', 'ADX', 'INFX', 'AGRS', 'GEO',
  'APX', 'BCY', 'FTC', 'THC', 'GOLOS', 'OK', 'UNB ', 'DAR', 'COVAL', 'PDC',
  'ION', 'RISE', 'NXC', 'EBST', 'NEOS', 'PINK', 'PPC', 'DYN', 'QWARK', 'LMC',
  'XST', 'CLUB', 'GRC', 'START', 'SBD', 'DMD', 'BLITZ ', 'CURE', 'PKB', 'TIME',
  'INCNT', 'CANN', 'EGC', 'BTCD', 'DOPE', 'UNO', 'AEON', 'CRB', 'FAIR', 'GCR',
  'NAUT', 'XVC', 'TRUST', 'EMC', 'SWT', 'RBY', 'FLDC ', 'ENRG', 'TX', 'FLO',
  'VTR', 'BRX', 'BSD', 'PTC', '2GIVE', 'SNRG', 'TRIG', 'ERC', 'BYC', 'SEQ',
  'SLR', 'AUR', 'SWIFT', 'GAM', 'TKS', 'CLAM'
];
