export const CONTRACT_STATE_INIT = 'INIT';
export const CONTRACT_STATE_ACCEPTED = 'ACCEPTED';
export const CONTRACT_STATE_VERIFIED = 'VERIFIED';
export const CONTRACT_STATE_FINISHED = 'FINISHED';
export const CONTRACT_STATE_HALTED = 'HALTED';
export const ESCAPE_KEYCODE = 27;